services:
  app:
    container_name: salary-hero
    entrypoint: ['/bin/sh', './entrypoint.sh']
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
       db:
        condition: service_healthy
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      - NODE_ENV=docker
  db:
    container_name: postgres
    image: postgres:15 
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5